FROM php:8.2-fpm

RUN apt-get update && \
    apt-get install -y git zip

RUN docker-php-ext-install pdo_mysql

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

USER 1000
