services:
  php:
    build:
      dockerfile: ./php/dockerfile
      context: .
    volumes:
      - ../:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    restart: always
    depends_on:
      - mysql
  
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    links:
      - php
    volumes:
      - ../:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: always
    depends_on:
      - php

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql/data:/var/lib/mysql
    restart: always

  adminer:
    image: adminer:latest
    ports:
      - 8081:8080
    restart: always
    depends_on:
      - mysql
